/**
 * Arabic string constants & RTL helpers for Grid Monitor (Yemen)
 * All user-facing text is defined here for consistency.
 */

import { I18nManager, StyleSheet, Platform } from 'react-native';

// Force RTL layout on app start
if (!I18nManager.isRTL) {
  I18nManager.allowRTL(true);
  I18nManager.forceRTL(true);
}

export const AR = {
  // ── App branding ─────────────────────────────────────────────────────────
  appName: 'مراقب الكهرباء',
  appTagline: 'نظام متابعة الكهرباء - اليمن',

  // ── Auth ─────────────────────────────────────────────────────────────────
  signIn: 'تسجيل الدخول',
  signOut: 'تسجيل الخروج',
  createAccount: 'إنشاء حساب',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  username: 'اسم المستخدم',
  enterEmailPassword: 'يرجى إدخال البريد الإلكتروني وكلمة المرور.',
  enterCredentials: 'أدخل بياناتك للمتابعة',
  noAccount: 'ليس لديك حساب؟  ',
  createAccountLink: 'إنشاء حساب',
  fillAllFields: 'يرجى تعبئة جميع الحقول.',
  passwordMin6: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل.',
  passwordsNoMatch: 'كلمات المرور غير متطابقة.',
  accountCreated: 'تم إنشاء الحساب!',
  accountCreatedBody: 'تم إنشاء حسابك. يرجى التحقق من بريدك الإلكتروني لتأكيد العنوان، ثم تسجيل الدخول.',
  goToSignIn: 'الذهاب لتسجيل الدخول',
  back: 'رجوع ←',
  joinNetwork: 'انضم إلى شبكة متابعة الكهرباء',
  displayNamePlaceholder: 'اسمك المعروض',
  emailPlaceholder: 'example@mail.com',
  minSixChars: 'الحد الأدنى 6 أحرف',
  reEnterPassword: 'أعد إدخال كلمة المرور',

  // ── Status ───────────────────────────────────────────────────────────────
  gridOn: 'الكهرباء شغالة',
  gridOff: 'الكهرباء طافية',
  gridOnShort: 'شغالة ⚡',
  gridOffShort: 'طافية 🔴',
  inverterOffline: '📡 الجهاز غير متصل',
  currentStatus: 'الحالة الحالية',
  currentStatusFull: 'الحالة الحالية للكهرباء',
  polled: 'آخر استعلام',
  for: 'منذ',
  gridInput: 'قدرة الشبكة',
  onSolarBattery: 'تعمل على الطاقة الشمسية / البطارية',

  // ── Prediction ───────────────────────────────────────────────────────────
  nextTransition: 'التغيير المتوقع القادم',
  gridExpectedOnIn: '⚡ الكهرباء متوقع اشتغالها خلال',
  gridExpectedOffIn: '🔴 الكهرباء متوقع طفوها خلال',
  predictionsUnavailable: '⚠️  التوقعات غير متاحة — النمط غير مستقر',
  confidence: 'مستوى الثقة',
  highConfidence: 'ثقة عالية',
  mediumConfidence: 'ثقة متوسطة',
  lowConfidence: 'ثقة منخفضة',
  veryLowConfidence: 'ثقة منخفضة جداً',
  veryHighConfidence: 'ثقة عالية جداً',
  patternStability: 'استقرار النمط',
  unstablePattern: 'نمط غير مستقر',
  stablePattern: 'مستقر',
  slightlyUnstablePattern: 'غير مستقر نسبياً',
  outageLength: 'مدة الانقطاع',
  gridOnLength: 'مدة تشغيل الكهرباء',
  in: 'خلال',
  nextTransitionLabel: 'التغيير القادم',
  patternShiftDetected: 'تغيّر في النمط',
  whyThisPrediction: '💡 لماذا هذا التوقع؟',
  mode: 'النوع',
  offset: 'الفارق',
  lastUpdated: 'آخر تحديث',
  learned: '🧠 مُتعلَّم',
  hybrid: '📊 مزيج',
  estimated: '📐 مقدّر',
  estBadge: 'تقديري',
  nowBadge: 'الآن',
  ongoing: '→ مستمر…',
  computedAt: 'حُسب الجدول في:',

  // ── Schedule ─────────────────────────────────────────────────────────────
  daySchedule: 'جدول اليوم',
  todaySchedule: 'جدول اليوم',
  scheduleTitle: 'جدول 24 ساعة القادمة (توقيت اليمن UTC+3)',
  yourOffset: 'فارقك الزمني',
  stability: 'الاستقرار',
  mySchedule: 'جدولي',
  noScheduleYet: 'لا يوجد جدول بعد',
  noScheduleSub: 'يُنشأ الجدول عند توفر بيانات كافية. يرجى المراجعة بعد دورة الكهرباء القادمة.',
  perCycle: 'لكل دورة',
  moreSlotsHint: '+{n} فترات أخرى — انظر تبويب الجدول',
  communitySync: 'مزامنة مجتمعية',
  communitySynced: '👥 مزامنة مجتمعية',
  adjustedViaCommunity: '👥 تم الضبط عبر بلاغ مجتمعي من',
  at: 'عند',

  // ── Zones ────────────────────────────────────────────────────────────────
  Night: 'الليل',
  Morning: 'الصباح',
  Midday: 'الظهيرة',
  Evening: 'المساء',
  'Late Night': 'منتصف الليل',

  // ── Home screen ──────────────────────────────────────────────────────────
  greeting: 'أهلاً،',
  setUpTiming: 'ضبط توقيتك',
  setUpTimingPrompt: 'اذهب إلى تبويب فارقي الزمني، أخبرنا متى آخر مرة تغيّرت الكهرباء، وسنحسب جدول حيّك الخاص.',
  calibrateNow: 'ضبط الآن ←',
  communitySyncedSchedule: '👥 تم مزامنة الجدول عبر بلاغ مجتمعي',
  commAlertsBanner: 'تنبيهات مجتمعية بانتظار ردّك',
  commAlert: 'تنبيه',
  commAlerts: 'تنبيهات',
  communityNetwork: 'شبكة المجتمع',
  reportGridTransition: 'أبلغ عن تغيّر في الكهرباء لتنبيه متابعيك',
  openArrow: 'فتح →',
  pendingAlerts: 'تنبيهات معلّقة من أشخاص تتابعهم',

  // ── Community ────────────────────────────────────────────────────────────
  communityTitle: 'المجتمع',
  nearby: 'القريبون',
  notifications: 'التنبيهات',
  history: 'السجل',
  following: 'أتابع',
  leaderboard: '🏆',
  yourReliability: 'موثوقيّتك',
  reports: 'بلاغات',
  responses: 'ردود',
  communityAlerts: 'تنبيهات المجتمع',
  allCaughtUp: 'لا توجد تنبيهات',
  awaitingResponse: 'بانتظار ردّك',
  resyncHistory: 'سجل المزامنة',
  lastNEvents: 'آخر {n} أحداث',
  followRequests: 'طلبات المتابعة',
  nearbyUsers: 'المستخدمون القريبون',
  withinHalfKm: 'ضمن 0.5 كم',
  noNearbyUsers: 'لا يوجد مستخدمون ضمن 0.5 كم',
  noNearbyUsersSub: 'شارك موقعك وادعُ الجيران للانضمام لمقارنة مواعيد الأحياء.',
  suggestedUsers: 'مستخدمون مقترحون',
  basedOnReliability: 'بناءً على الموثوقية وسلوك الكهرباء',
  follow: 'متابعة',
  unfollow: 'إلغاء المتابعة',
  followPending: '⏳ معلّق',
  followAccept: '← قبول',
  followingLabel: 'يتابعون',
  yourFollowers: 'متابعوك',
  sentRequests: 'طلبات مُرسَلة',
  noConnections: 'لا توجد اتصالات بعد',
  noConnectionsSub: 'اذهب إلى تبويب القريبون للبحث عن مستخدمين موثوقين.',
  receivesYourAlerts: 'يستقبل تنبيهاتك عن الكهرباء',
  youReceiveAlerts: 'تستقبل تنبيهاته عن الكهرباء',
  requestPending: 'طلب بانتظار الموافقة',
  remove: 'إزالة',
  cancel: 'إلغاء',
  accept: 'قبول',
  decline: 'رفض',
  wantsToFollow: 'يريد متابعتك',
  reliabilityLabel: 'موثوقية',
  reportsLabel: 'بلاغات',
  offsetLabel: 'الفارق',
  lastActive: 'آخر نشاط',
  away: 'بعيد',
  noHistory: 'لا يوجد سجل بعد',
  noHistorySub: 'عندما تؤكد بلاغاً مجتمعياً، يظهر هنا سجل المزامنة.',
  noAlerts: 'لا توجد تنبيهات',
  noAlertsSub: 'عندما يُبلّغ شخص تتابعه عن تغيّر، يظهر التنبيه هنا لمدة 30 دقيقة.',
  reportedBy: 'أبلغ',
  electricityCameOn: 'اشتغلت الكهرباء',
  electricityWentOff: 'طفت الكهرباء',
  isThisCorrect: 'هل هذا صحيح في موقعك؟',
  expired: 'انتهت الصلاحية',
  minutesLeft: 'د متبقية',
  yesBtn: '✅  نعم',
  noBtn: '❌  لا',
  skipBtn: 'تخطي',
  youConfirmedYes: '✅ أكدت بنعم',
  youSaidNo: '❌ قلت لا',
  ignored: '⏭ تم التجاهل',
  effective: 'الوقت الفعلي:',
  reportedByLabel: 'أبلغ عنه:',
  confirmedAt: '· أُكّد في',
  communityLabel: '👥 مجتمعي',

  // ── Participation restriction ─────────────────────────────────────────────
  communityAlertsRestricted: 'التنبيهات المجتمعية محظورة',
  ignoreRateTooHigh: 'معدل التجاهل مرتفع جداً ({pct}% من {total} إشعار). رُدّ على التنبيهات القادمة لاستعادة الوصول تلقائياً.',

  // ── Report Modal ──────────────────────────────────────────────────────────
  reportUtilityTransition: 'الإبلاغ عن تغيير حالة الكهرباء',
  reportSubtitle: 'شارك ما حدث لكي يتمكن متابعوك من مزامنة جداولهم',
  whatHappened: 'ماذا حدث؟',
  whenHappened: 'متى حدث؟',
  cameOn: 'الكهرباء اشتغلت',
  wentOff: 'الكهرباء طفت',
  shareWithFollowers: '📢  مشاركة مع المتابعين',
  reportTransitionBtn: '📢  الإبلاغ عن تغيير',
  cooldownText: '⏳ يمكنك الإبلاغ مجدداً خلال {label}',
  reportShared: 'تم إرسال البلاغ',
  reportSharedBody: 'تم تحديث جدولك وتم إخطار متابعيك.',

  // ── Time options ─────────────────────────────────────────────────────────
  timeNow: 'الآن',
  time5min: 'منذ ~5 دقائق',
  time10min: 'منذ ~10 دقائق',
  time15min: 'منذ ~15 دقيقة',
  time20min: 'منذ ~20 دقيقة',

  // ── Location ─────────────────────────────────────────────────────────────
  gettingLocation: 'جارٍ تحديد الموقع…',
  locationDenied: '📍 تم رفض الموقع — اسمح بالوصول في الإعدادات للعثور على المستخدمين القريبين',
  tryAgain: 'إعادة المحاولة',
  shareMyLocation: '📍  مشاركة موقعي',
  locationShared: '✓ تمت مشاركة الموقع!',

  // ── Calibrate screen ─────────────────────────────────────────────────────
  calibrateTitle: 'معايرة توقيتي',
  howOffsetWorks: 'كيف يعمل فارقك الزمني',
  howOffsetExplain: 'الجهاز الرئيسي يسجّل أحداث الكهرباء للشبكة الرئيسية. قد يصلك التيار في وقت مختلف قليلاً — ربما قبل 15 دقيقة أو بعد 30 دقيقة.\n\nأخبرنا متى آخر مرة لاحظت تغيّر الكهرباء، وسنحسب الفارق الدقيق لحيّك. كل التوقعات ستُعدَّل تلقائياً لموقعك.',
  yourCurrentOffset: 'فارقك الزمني الحالي',
  blockMatchesMain: 'حيّك يتزامن مع الشبكة الرئيسية',
  blockAfter: 'حيّك يحصل على الكهرباء بعد المقياس الرئيسي بـ',
  blockBefore: 'حيّك يحصل على الكهرباء قبل المقياس الرئيسي بـ',
  lastCalibratedWith: 'آخر معايرة باستخدام:',
  step1: 'الخطوة 1 — ما الحدث الذي لاحظته؟',
  step2: 'الخطوة 2 — في أي وقت؟ (توقيت اليمن UTC+3)',
  powerWentOff: 'الكهرباء طفت',
  gridWentOut: 'ذهبت الشبكة',
  powerCameOn: 'الكهرباء اشتغلت',
  gridCameBack: 'عادت الشبكة',
  powerWentOffAt: '🔴 الكهرباء طفت في هذا الوقت',
  powerCameOnAt: '⚡ الكهرباء اشتغلت في هذا الوقت',
  calibrateBtn: '⚡  احسب فارقي الزمني',
  updateOffsetBtn: '↻  تحديث فارقي الزمني',
  skipNote: 'يمكنك تخطي المعايرة وسيستخدم التطبيق بيانات Growatt مباشرة بدون فارق (0 دقيقة). يمكنك المعايرة في أي وقت لتخصيص توقعاتك.',
  couldNotCalibrate: 'تعذّرت المعايرة',
  calibrationHint: 'تأكد من وجود أحداث كهرباء حديثة خلال آخر 48 ساعة.',
  calibrated: '✅ تمت المعايرة!',
  yourBlockIs: 'حيّك يتأخر',
  beforeMain: 'قبل',
  afterMain: 'بعد',
  readingsAdjusted: 'قراءات Growatt الرئيسية.\nكل التوقعات معدّلة الآن لموقعك.',
  communityImpactWeek: 'تأثير المجتمع هذا الأسبوع',
  scheduleAdjustments: 'تعديلات الجدول',
  avgDelta: 'متوسط الفرق',
  topReporter: 'أفضل مُبلِّغ',
  noImpactYet: 'لا توجد مزامنات مجتمعية بعد هذا الأسبوع. تابع المستخدمين القريبين وردّ على بلاغاتهم لترى تأثيرك هنا.',
  calculatingImpact: 'جارٍ حساب التأثير…',
  communityImpactHint: 'ضبطت بلاغات المجتمع جدولك {count} {times} هذا الأسبوع بمتوسط تصحيح {delta} دقيقة. ابقَ نشطاً لتستمر في الحصول على التنبيهات.',
  timesWord: 'مرة',
  timesWordPlural: 'مرات',
  autoSuggestTitle: 'المجتمع يقترح تحديث الفارق الزمني',
  autoSuggestBody: 'بناءً على {count} مزامنات مجتمعية متسقة هذا الأسبوع، تصل الكهرباء إلى حيّك {direction}.',
  eventsAgree: 'كل {count} أحداث متفقة ضمن {spread} دقيقة من بعضها.',
  laterThanExpected: 'متأخرة بـ {n} دقيقة عن التوقع',
  earlierThanExpected: 'مبكرة بـ {n} دقيقة عن التوقع',
  current: 'الحالي',
  suggested: 'المقترح',
  applySuggested: '⚡  تطبيق الفارق المقترح',
  notNow: 'ليس الآن',

  // ── Settings ─────────────────────────────────────────────────────────────
  profile: 'الملف الشخصي',
  settings: 'الإعدادات',
  myProfileSettings: 'ملفي الشخصي والإعدادات',
  displayName: 'الاسم المعروض',
  displayNameHint: 'يظهر هذا الاسم للمستخدمين الآخرين في تبويب المجتمع. استخدم 3–30 حرفاً: حروف أو أرقام أو شرطة سفلية أو شرطة أو نقطة.',
  noUsername: 'لا يوجد اسم مستخدم',
  usernameUpdated: '✅ تم تحديث الاسم!',
  edit: 'تعديل',
  saveName: 'حفظ الاسم',
  usernameTooShort: 'يجب أن يكون 3 أحرف على الأقل.',
  usernameTooLong: 'يجب ألا يتجاوز 30 حرفاً.',
  usernameInvalidChars: 'يُسمح فقط بالحروف والأرقام والشرطة السفلية والشرطة والنقطة.',
  usernameEmpty: 'لا يمكن أن يكون الاسم فارغاً.',
  notificationSound: 'صوت الإشعار',
  playSoundOnChange: 'تشغيل صوت عند تغيّر الكهرباء',
  diagnostics: 'الفحص والتشخيص',
  testNotifDesc: 'أرسل إشعار تجريبي للتحقق من أن التنبيهات تعمل على جهازك.',
  testNotifDescSound: ' سيُشغَّل الصوت.',
  testNotifDescNoSound: ' الصوت معطّل.',
  sendTestNotif: '🔔  إرسال إشعار تجريبي',
  notifSent: '✓ تم إرسال الإشعار!',
  permDenied: '✗ تم رفض الإذن',
  permDeniedHint: 'يرجى السماح بالإشعارات في إعدادات الجهاز.',
  about: 'حول التطبيق',
  app: 'التطبيق',
  dataSource: 'مصدر البيانات',
  dangerZone: 'منطقة الخطر',
  deleteMyAccount: 'حذف حسابي',
  deleteAccountDesc: 'يحذف حسابك نهائياً وجميع بلاغاتك واتصالاتك وسجل المزامنة وبيانات الفارق الزمني. لا يمكن التراجع.',
  deleteAccountBtn: '🗑️  حذف حسابي',
  deleteAccountConfirmTitle: 'حذف الحساب',
  deleteAccountConfirmBody: 'سيحذف هذا حسابك وجميع البلاغات وإتصالات المتابعة وسجل المزامنة نهائياً. لا يمكن التراجع.',
  deleteForever: 'حذف نهائياً',
  deleteAccountFinal: 'هل أنت متأكد تماماً؟',
  deleteAccountFinalBody: 'سيُحذف حسابك المرتبط بـ {email} بشكل دائم.',
  yesDelete: 'نعم، احذف',
  deleteError: 'فشل حذف الحساب. يرجى المحاولة مجدداً.',
  signOutConfirmTitle: 'تسجيل الخروج',
  signOutConfirmBody: 'هل أنت متأكد من تسجيل الخروج؟',
  adminRole: '🛡 مشرف',
  userRole: '👤 مستخدم',
  footer: 'التوقعات مبنية على الأنماط التاريخية وقد لا تكون دقيقة 100٪. تحقق دائماً من ظروفك المحلية.',

  // ── Admin panel ───────────────────────────────────────────────────────────
  adminPanel: 'لوحة الإدارة',
  growattMonitor: 'مراقب Growatt',
  growattSub: 'KHM8EYS0SC · اليمن',
  adminBadge: '⚙️ مشرف',
  solarBattery: '☀️  طاقة شمسية + بطارية BYD',
  pollsEvery5: '🔄  استعلام كل 5 دقائق',
  smartPrediction: '🔮  التوقع الذكي',
  tapForFullAnalysis: 'اضغط للتحليل الكامل  ›',
  recentEvents: 'الأحداث الأخيرة',
  total: 'الإجمالي',
  noEventsYet: 'لا توجد أحداث بعد',
  noEventsSub: 'تظهر الأحداث عند تغيّر حالة الكهرباء.',
  communityResync: '👥  المزامنة المجتمعية',
  noResyncYet: 'لا توجد مزامنات بعد. عندما يؤكد المستخدمون بلاغات الكهرباء، تظهر هنا.',
  conflictBtn: '⚠ {n} تعارض',
  conflictsBtn: '⚔ التعارضات',
  confirmed: 'أُكّد',
  reliability: 'الموثوقية',
  historyNav: '📋  السجل',
  predictionsNav: '🔮  التوقعات',
  settingsNav: '⚙️  الإعدادات',
  loadingEvents: 'جارٍ تحميل الأحداث…',
  unstableNotEnoughData: '⚠️  النمط غير مستقر — بيانات غير كافية',
  nextTransitionLabel2: 'التغيير القادم',
  gridWillTurnOn: 'الكهرباء ستشتغل',
  gridWillTurnOff: 'الكهرباء ستطفى',

  // ── History screen ────────────────────────────────────────────────────────
  powerHistory: 'سجل الكهرباء',
  totalLabel: 'الإجمالي',
  gridOnLabel: 'شغّالة',
  gridOffLabel: 'طافية',
  daysLabel: 'أيام',
  chartTab: '📊 مخطط',
  dailyTab: '📅 يومي',
  eventsTab: '📋 أحداث',
  tapToEditDelete: 'اضغط على أي حدث لتعديله أو حذفه',
  onOffHoursByPeriod: 'ساعات التشغيل/الانقطاع حسب الفترة',
  recentDays: 'الأيام الأخيرة',
  noChartData: 'لا توجد بيانات للمخطط بعد',
  noStats: 'لا توجد إحصائيات بعد',
  noEvents: 'لا توجد أحداث',
  days7: '7 أيام',
  days30: '30 يوماً',
  uptime: 'وقت التشغيل',
  outage: 'الانقطاع',
  grid: 'الشبكة',
  avgOn: 'متوسط الشغّال',
  avgOff: 'متوسط الطافي',
  outages: 'انقطاعات',
  editTimestamp: 'تعديل التوقيت',
  deleteEvent: 'حذف الحدث',
  editEventTitle: 'تعديل وقت الحدث',
  editEventSub: 'الحدث:',
  dateTimeFmt: 'التاريخ والوقت (توقيت اليمن UTC+3)',
  formatHint: 'الصيغة: YYYY-MM-DD HH:MM',
  invalidFormat: 'الصيغة يجب أن تكون YYYY-MM-DD HH:MM (توقيت اليمن)',
  invalidDateTime: 'تاريخ/وقت غير صحيح',
  saving: 'جارٍ الحفظ…',
  utilityCameOn: 'الكهرباء اشتغلت',
  utilityWentOff: 'الكهرباء طفت',
  deleteEventConfirm: 'هل أنت متأكد من حذف هذا الحدث؟',
  delete: 'حذف',
  events: 'حدث',
  eventPlural: 'أحداث',

  // ── Predictions screen ────────────────────────────────────────────────────
  smartPredictions: 'التوقعات الذكية',
  analyzingPatterns: 'جارٍ تحليل الأنماط…',
  noAnalysisYet: 'لا يوجد تحليل بعد',
  pullToTrigger: 'اسحب للأسفل لتشغيل محرك التحليل.',
  runAnalysisNow: 'تشغيل التحليل الآن',
  fetchingLatest: 'جارٍ جلب أحدث تحليل APPPE…',
  currentState: 'الحالة الحالية',
  dayTime: '☀️ نهار',
  nightTime: '🌙 ليل',
  predictionConfidence: 'مستوى الثقة في التوقع',
  nextTransitionCard: 'التغيير القادم',
  dayNightPatterns: 'أنماط النهار والليل',
  cyclesAnalyzed: 'دورة محللة',
  dayLabel: 'نهار',
  nightLabel: 'ليل',
  patternStabilityCard: 'استقرار النمط',
  stableDesc: 'دورات منتظمة. التوقعات موثوقة.',
  slightlyUnstableDesc: 'تذبذب نسبي. استخدم التوقعات كمرشد تقريبي.',
  unstableDesc: 'تذبذب عالٍ. الجدول يتغيّر بشكل متكرر.',
  apppeProfileBlend: 'مزيج نماذج APPPE',
  learningProgress: 'تقدم التعلّم',
  daysOfRealData: 'أيام من البيانات الحقيقية',
  priorOnly: 'تقديرات فقط',
  hybridMode: 'مزيج',
  learnedMode: 'مُتعلَّم',
  priorOnlyDesc: 'تقديرات فقط — بيانات غير كافية، نستخدم تقديرات إحصائية مُحكَمة',
  hybridDesc: 'مزيج — دمج البيانات المتعلَّمة مع التقديرات الإحصائية',
  learnedDesc: 'مُتعلَّم بالكامل — التوقعات مبنية على بيانات تاريخية حقيقية',
  totalCycles: 'إجمالي الدورات عبر كل النماذج',
  cycleWord: 'دورة',
  cyclesWord: 'دورات',
  blendsSmoothly: 'تتمازج النماذج بسلاسة مع الوقت — لا حدود ثابتة. مجموع الأوزان 100٪.',
  analysisReasoning: 'تحليل وتفسير',
  lastComputed: 'آخر حساب:',
  reanalyzeNow: '🔄  إعادة التحليل الآن',
  noData: 'لا توجد بيانات',
  samples: 'عينة',
  samplesPlural: 'عينات',
  noDataCycles: 'لا توجد دورات',
  dominant: 'المسيطر:',
  dayPattern: '☀️ نهار (6 صباحاً – 6 مساءً)',
  nightPattern: '🌙 ليل (6 مساءً – 6 صباحاً)',
  avgOffLabel: 'متوسط الانقطاع',
  avgOnLabel: 'متوسط التشغيل',

  // ── Admin settings ────────────────────────────────────────────────────────
  adminAccount: '⚙️  حساب المشرف',
  pushTokenAdmin: '📱  رمز الإشعار — جهاز المشرف',
  adminTokenOk: 'هذا الجهاز مُعلَّم كجهاز مشرف — سيستقبل الإشعارات.',
  adminTokenNotMarked: 'هذا الجهاز ليس مُعلَّماً كمشرف بعد.',
  adminTokenNotReg: 'الرمز غير مسجّل بعد. اضغط "تعليم كمشرف" أدناه.',
  markAdminDesc: 'علِّم هذا الجهاز كجهاز مشرف لتستقبل الإشعارات الفورية وصوت التنبيه عند كل تغيّر في الكهرباء.',
  markAsAdmin: '📍  تعليم هذا الجهاز كمشرف',
  notOnWeb: 'غير متاح في المعاينة عبر الإنترنت. استخدم جهازاً حقيقياً أو APK.',
  permissionDenied: 'الإذن مرفوض',
  allowNotifications: 'يرجى السماح بالإشعارات في إعدادات الجهاز أولاً.',
  noProjectId: 'لا يوجد معرّف مشروع',
  notificationsSection: '🔔  الإشعارات',
  soundAlarm: 'صوت التنبيه',
  playAlarmDesc: 'تشغيل صوت عند تشغيل/إيقاف الكهرباء',
  alarmDuration: 'مدة التنبيه ({n} ثانية)',
  alarmDurationDesc: 'مدة تشغيل الصوت داخل التطبيق',
  communityConflicts: '⚔  التعارضات المجتمعية',
  conflictsDesc: '{n} تعارض غير مراجَع حيث تختلف البلاغات مع بيانات المقياس',
  conflictsOkDesc: 'جميع البلاغات المجتمعية متوافقة مع بيانات المقياس',
  patternProfiles: '🧠  نماذج الأنماط',
  noApppeData: 'لا توجد بيانات APPPE بعد — شغّل التحليل أولاً.',
  patternStatsHint: 'أعداد العينات من آخر 7 أيام. الاستقرار والثقة يعكسان أوزان النماذج الحالية.',
  patternShiftActive: '⚠️  وضع تغيّر الأنماط نشط',
  medOff: 'الوسيط طافي',
  medOn: 'الوسيط شغّال',
  blend: 'المزيج',
  overallStability: 'الاستقرار الكلي',
  testSection: '🧪  اختبار الإشعارات',
  testSectionDesc: 'أرسل إشعاراً تجريبياً للتحقق من إعدادات الجهاز.',
  testOn: '⚡  اختبار: شغّالة',
  testOff: '🔴  اختبار: طافية',
  sending: 'جارٍ الإرسال…',
  settingsSaved: '✓  تم حفظ الإعدادات',
  signOutAdmin: 'تسجيل الخروج',

  // ── Conflicts screen ──────────────────────────────────────────────────────
  conflictsTitle: 'التعارضات المجتمعية',
  growattSensor: 'مستشعر Growatt',
  communityReport: 'بلاغ المجتمع',
  adminNotes: 'ملاحظات المشرف',
  addNotes: 'أضف ملاحظاتك حول هذا التعارض (اختياري)…',
  markAsReviewed: '✓  تعليم كـ مراجَع',
  pendingFilter: 'معلّق',
  allFilter: 'الكل',
  reviewedFilter: 'تمت المراجعة',
  conflictHash: 'تعارض #',
  reviewed: '✓ تمت المراجعة',
  pending: '⚠ معلّق',
  growattLabel: 'GROWATT',
  reportedLabel: 'المُبلَّغ',
  reporterLabel: 'المُبلِّغ',
  timeLabel: 'الوقت',
  reportedAt: 'أُبلغ عنه في',
  reviewConflict: 'مراجعة هذا التعارض',
  noPendingConflicts: 'لا توجد تعارضات معلّقة',
  noConflictsFound: 'لا توجد تعارضات',
  allInAgreement: 'جميع البلاغات متوافقة مع بيانات مستشعر Growatt.',
  dataConsistent: 'البلاغات وبيانات المستشعر كانت متسقة.',
  loadingConflicts: 'جارٍ تحميل التعارضات…',
  reviewConflictTitle: 'مراجعة التعارض',
  unreviewed: 'غير مراجَع',

  // ── General ───────────────────────────────────────────────────────────────
  loading: 'جارٍ التحميل…',
  loadingYourTiming: 'جارٍ تحميل توقيتك…',
  noInternetConnection: 'لا يوجد اتصال بالإنترنت',
  failedToLoadData: 'فشل تحميل البيانات',
  somethingWentWrong: 'حدث خطأ غير متوقع',
  tryAgainBtn: 'إعادة المحاولة',
  error: 'خطأ',
  ok: 'موافق',
  save: 'حفظ',
  hour: 'ساعة',
  hours: 'ساعات',
  minute: 'دقيقة',
  minutes: 'دقائق',
  today: 'اليوم',
  yesterday: 'أمس',
  monday: 'الاثنين',
  tuesday: 'الثلاثاء',
  wednesday: 'الأربعاء',
  thursday: 'الخميس',
  friday: 'الجمعة',
  saturday: 'السبت',
  sunday: 'الأحد',
  scheduleUpdated: 'تم تحديث الجدول',
  scheduleUpdatedBody: 'تم إعادة مزامنة جدولك الشخصي بناءً على هذا البلاغ المجتمعي.',

  // ── ATC — Adaptive Transition Controller ─────────────────────────────────
  atcUnusualContinuation: 'استمرار غير معتاد',
  atcWaitingConfirmation: 'بانتظار تأكيد تغير الحالة',
  atcWaitingGrowatt: 'بانتظار تأكيد الحساس الرئيسي',
  atcCommunitySynced: '🔄 تمت مزامنة الحالة عبر المجتمع',
  atcGraceWarning: 'تأخر غير معتاد',
  atcGraceBody: 'لا يزال التشغيل مستمراً خارج النطاق المتوقع',
  atcUncertainBody: 'لا يزال التغيير متوقعاً — النمط الحالي ممتد بشكل غير معتاد',
  atcWaitingGrowattBody: 'بانتظار تأكيد الحساس الرئيسي أو بلاغ مجتمعي',
  atcInPredictionRange: 'نطاق التوقع نشط — التغيير محتمل',
  atcCommunityHighPriority: '👥 بلاغات المجتمع ذات أولوية مرتفعة الآن',
};

/** Format duration in Arabic */
export function fmtAr(min: number): string {
  if (min <= 0) return '0 د';
  const h = Math.floor(min / 60);
  const m = Math.round(min % 60);
  if (h === 0) return `${m} د`;
  if (m === 0) return h === 1 ? 'ساعة' : h === 2 ? 'ساعتان' : `${h} ساعات`;
  return `${h}س ${m}د`;
}

/** Common RTL-aware style additions */
export const rtl = StyleSheet.create({
  text: { textAlign: 'right', writingDirection: 'rtl' },
  row: { flexDirection: 'row-reverse' },
  rowKeepNormal: { flexDirection: 'row' }, // use when order must stay
});
